# Generated by Django 2.2.14 on 2020-12-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201122_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
                ('descuento', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
